BEGIN;

INSERT INTO cities (name, state) VALUES
    ('Bielsko-Biała', 'Silesian'),
    ('Bieruń', 'Silesian'),
    ('Blachownia', 'Silesian'),
    ('Bytom', 'Silesian'),
    ('Będzin', 'Silesian'),
    ('Chorzów', 'Silesian'),
    ('Cieszyn', 'Silesian'),
    ('Czechowice-Dziedzice', 'Silesian'),
    ('Czeladź', 'Silesian'),
    ('Czerwionka-Leszczyny', 'Silesian'),
    ('Częstochowa', 'Silesian'),
    ('Dąbrowa Górnicza', 'Silesian'),
    ('Gliwice', 'Silesian'),
    ('Imielin', 'Silesian'),
    ('Jastrzębie-Zdrój', 'Silesian'),
    ('Jaworzno', 'Silesian'),
    ('Kalety', 'Silesian'),
    ('Katowice', 'Silesian'),
    ('Knurów', 'Silesian'),
    ('Koniecpol', 'Silesian'),
    ('Koziegłowy', 'Silesian'),
    ('Krzanowice', 'Silesian'),
    ('Krzepice', 'Silesian'),
    ('Kuźnia Raciborska', 'Silesian'),
    ('Kłobuck', 'Silesian'),
    ('Lubliniec', 'Silesian'),
    ('Lędziny', 'Silesian'),
    ('Miasteczko Śląskie', 'Silesian'),
    ('Mikołów', 'Silesian'),
    ('Myszków', 'Silesian'),
    ('Mysłowice', 'Silesian'),
    ('Ogrodzieniec', 'Silesian'),
    ('Orzesze', 'Silesian'),
    ('Piekary Śląskie', 'Silesian'),
    ('Pilica', 'Silesian'),
    ('Poręba', 'Silesian'),
    ('Pszczyna', 'Silesian'),
    ('Pszów', 'Silesian'),
    ('Pyskowice', 'Silesian'),
    ('Racibórz', 'Silesian'),
    ('Radlin', 'Silesian'),
    ('Radzionków', 'Silesian'),
    ('Ruda Śląska', 'Silesian'),
    ('Rybnik', 'Silesian'),
    ('Rydułtowy', 'Silesian'),
    ('Siemianowice Śląskie', 'Silesian'),
    ('Siewierz', 'Silesian'),
    ('Skoczów', 'Silesian'),
    ('Sosnowiec', 'Silesian'),
    ('Sośnicowice', 'Silesian'),
    ('Strumień', 'Silesian'),
    ('Szczekociny', 'Silesian'),
    ('Szczyrk', 'Silesian'),
    ('Sławków', 'Silesian'),
    ('Tarnowskie Góry', 'Silesian'),
    ('Toszek', 'Silesian'),
    ('Tychy', 'Silesian'),
    ('Ustroń', 'Silesian'),
    ('Wilamowice', 'Silesian'),
    ('Wisła', 'Silesian'),
    ('Wodzisław Śląski', 'Silesian'),
    ('Wojkowice', 'Silesian'),
    ('Woźniki', 'Silesian'),
    ('Zabrze', 'Silesian'),
    ('Zawiercie', 'Silesian'),
    ('Łaziska Górne', 'Silesian'),
    ('Łazy', 'Silesian'),
    ('Świętochłowice', 'Silesian'),
    ('Żarki', 'Silesian'),
    ('Żory', 'Silesian'),
    ('Żywiec', 'Silesian')
    ON CONFLICT DO NOTHING;

COMMIT;